version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello world" > output.txt
      - persist_to_workspace:
          root: ~/
          path:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  print-helloworld:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-myname:
          requires:
            - print-world
